version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    env_file: ["./Db/config"]
    ports:
        - 1433:1433
    volumes: ["/home/andre/base_relacionamento:/var/opt/mssql/data"]